// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfvgprmiuezxksndunyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmdmdwcm1pdWV6eGtzbmR1bnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5ODYwNDEsImV4cCI6MjA4OTU2MjA0MX0.gHe4dRHcE8uuP37IxAUXxEP-N7DZuQi6tgV7ZFc4CUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});